### ISSUE TITLE
Add a DOMAIN parameter?

### ISSUE THREAD

**Issue by Spritekin** [tobilg/docker-mesos-dns#2]
Hi,
Just wanted to drop a message. This image may be the easiest image to configure from all the mesos-dns images I have tried.

Thanks!

**Comment by tobilg** [comment]
Thanks a lot! Domain support was added in https://github.com/tobilg/docker-mesos-dns/commit/1f80f27844bb06d739e5768c759a73594ef3a796. You'll need to use the `latest` Docker image currently, because I wanted to be aligned with the Mesos DNS releases, I didn't create a new tag...
